#!/bin/sh
#package for testing deb and rpm repos  https://safrm.net/projects/repotest
#author:  Miroslav Safr <miroslav.safr@gmail.com>
VERSION=NA
VERSION_DATE=NA

fail() { printf "\n\033[01;31mERROR: $*\033[00m\n" ; exit 1 ; }
verbose(){ [ ${VERBOSE_FLAG:-0} -eq 0 ] || echo "\033[36m$*\033[00m" ; }
usage() {
    echo "`basename $0` ${VERSION} - Simple generic backup "
    echo " http://safrm.net/projects/repotest"
    echo "Usage:`basename $0` [OPTIONS]"
    echo " options: "
    echo " -v,  --verbose  ...................... prints mor output"
    echo " -h,  --help .......................... shows command line help"
    echo " -V,  --version  ...................... prints version of scripts"
    echo ""
}

while [ $# -gt 0 ]; do
    case "$1" in
        -V|--version)       echo "`basename $0` ${VERSION} ${VERSION_DATE}"; exit 0 ;;
        -h|--help)          usage ; exit ;;
        -v|--verbose)       VERBOSE_FLAG=1 ;;
        *)                  fail "unknown option $1" ;;
    esac
    shift
done

if [ ${VERBOSE_FLAG:-0} -eq 0 ]; then
    APTCACHE=`which apt-cache 2>/dev/null`
    YUM=`which yum 2>/dev/null`
    echo "script version: $VERSION - $VERSION_DATE"
    if [ -n "$APTCACHE" ]; then
        apt-cache policy repotest 2>&1
    elif [ -n "$YUM" ]; then
        yum list available repotest 2>&1
    else 
        fail "no supported repomanager found"
    fi
fi

